version: "3.3"

services:
  olx-monitor-nginx:
    image: nginx:1.21.1-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
  olx-monitor:
    build: .
    image: olx-monitor:latest
    restart: always
    depends_on:
      - olx-monitor-database
      - olx-monitor-nginx
    environment:
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_TOKEN=${BOT_TOKEN}
  olx-monitor-database:
    image: postgres:14.1
    container_name: olx-monitor-database
    restart: always
    environment:
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=olx-monitor-db
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/