spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olx-monitor-db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
telegram-bot:
  username: optional:file:.env[BOT_USERNAME]
  token: 5014015511:AAH3kQGXlnXWZEdaw3MqxEwRM7JcHsNHxQ4